#!/bin/bash

export SFCGAL_HOME=$SFCGAL130_HOME
export CGAL_HOME=$CGAL39_HOME
export BOOST_HOME=$BOOST155_HOME
export BOOST_ROOT=$BOOST_HOME

export PATH=$SFCGAL_HOME/bin:${PATH}

export LD_RUN_PATH=$SFCGAL_HOME/lib64:$BOOST_HOME/lib:$CGAL_HOME/lib:$LD_RUN_PATH
export LD_LIBRARY_PATH=$SFCGAL_HOME/lib64:$BOOST_HOME/lib:$CGAL_HOME/lib:$LD_LIBRAYR_PATH
export LIBRARY_PATH=$SFCGAL_HOME/lib64:$BOOST_HOME/lib:$CGAL_HOME/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=$SFCGAL_HOME/include:$CGAL_HOME/include:${C_INCLUDE_PATH}

