#!/bin/bash

export LIBLAS_HOME=$LIBLAS170_HOME
export LASZIP_HOME=$LASZIP210_HOME
export SFCGAL_HOME=$SFCGAL_130_HOME/install_optimized
export CGAL_HOME=$CGAL_481_HOME/install_optimized
export BOOST_HOME=$BOOST155_HOME
export BOOST_ROOT=$BOOST_HOME

export PATH=$SFCGAL_HOME/bin:${PATH}

export LD_RUN_PATH=$SFCGAL_HOME/lib64:$BOOST_HOME/lib:$CGAL_HOME/lib:$LASZIP_HOME/lib:$LIBLAS_HOME/lib:$LD_RUN_PATH
export LD_LIBRARY_PATH=$SFCGAL_HOME/lib64:$BOOST_HOME/lib:$CGAL_HOME/lib:$LASZIP_HOME/lib:$LIBLAS_HOME/lib:$LD_LIBRAYR_PATH
export LIBRARY_PATH=$SFCGAL_HOME/lib64:$BOOST_HOME/lib:$CGAL_HOME/lib:$LASZIP_HOME/lib:$LIBLAS_HOME/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=$SFCGAL_HOME/include:$CGAL_HOME/include:$LIBLAS_HOME/include/liblas/capi:${C_INCLUDE_PATH}

