alter table bgt_begroeidterreindeel add column col_type string;
alter table bgt_ondersteunendwaterdeel add column col_type string;
alter table bgt_onbegroeidterreindeel add column col_type string;
alter table bgt_ondersteunendwegdeel add column col_type string;
alter table bgt_overbruggingsdeel add column col_type string;
alter table overbruggingsdeel add column col_type string;
alter table bgt_overigbouwwerk add column col_type string;
alter table bgt_pand add column col_type string;
alter table bgt_scheiding add column col_type string;
alter table bgt_tunneldeel add column col_type string;
alter table bgt_waterdeel add column col_type string;
alter table bgt_wegdeel add column col_type string;
alter table bgt_paal add column col_type string;
alter table bgt_kunstwerkdeel add column col_type string;

update bgt_begroeidterreindeel set col_type = ST_GeometryType(wkt);
update bgt_ondersteunendwaterdeel set col_type = ST_GeometryType(wkt);
update bgt_onbegroeidterreindeel set col_type = ST_GeometryType(wkt);
update bgt_ondersteunendwegdeel set col_type = ST_GeometryType(wkt);
update bgt_overbruggingsdeel set col_type = ST_GeometryType(wkt);
update overbruggingsdeel set col_type = ST_GeometryType(wkt);
update bgt_overigbouwwerk set col_type = ST_GeometryType(wkt);
update bgt_pand set col_type = ST_GeometryType(wkt);
update bgt_scheiding set col_type = ST_GeometryType(wkt);
update bgt_tunneldeel set col_type = ST_GeometryType(wkt);
update bgt_waterdeel set col_type = ST_GeometryType(wkt);
update bgt_wegdeel set col_type = ST_GeometryType(wkt);
update bgt_paal set col_type = ST_GeometryType(wkt);
update bgt_kunstwerkdeel set col_type = ST_GeometryType(wkt);
