alter table bgt_begroeidterreindeel add column col_isvalid boolean;
alter table bgt_ondersteunendwaterdeel add column col_isvalid boolean;
alter table bgt_onbegroeidterreindeel add column col_isvalid boolean;
alter table bgt_ondersteunendwegdeel add column col_isvalid boolean;
alter table bgt_overbruggingsdeel add column col_isvalid boolean;
alter table overbruggingsdeel add column col_isvalid boolean;
alter table bgt_overigbouwwerk add column col_isvalid boolean;
alter table bgt_pand add column col_isvalid boolean;
alter table bgt_scheiding add column col_isvalid boolean;
alter table bgt_tunneldeel add column col_isvalid boolean;
alter table bgt_waterdeel add column col_isvalid boolean;
alter table bgt_wegdeel add column col_isvalid boolean;
alter table bgt_paal add column col_isvalid boolean;
alter table bgt_kunstwerkdeel add column col_isvalid boolean;

update bgt_begroeidterreindeel set col_isvalid = ST_IsValid(wkt);
update bgt_ondersteunendwaterdeel set col_isvalid = ST_IsValid(wkt);
update bgt_onbegroeidterreindeel set col_isvalid = ST_IsValid(wkt);
update bgt_ondersteunendwegdeel set col_isvalid = ST_IsValid(wkt);
update bgt_overbruggingsdeel set col_isvalid = ST_IsValid(wkt);
update overbruggingsdeel set col_isvalid = ST_IsValid(wkt);
update bgt_overigbouwwerk set col_isvalid = ST_IsValid(wkt);
update bgt_pand set col_isvalid = ST_IsValid(wkt);
update bgt_scheiding set col_isvalid = ST_IsValid(wkt);
update bgt_tunneldeel set col_isvalid = ST_IsValid(wkt);
update bgt_waterdeel set col_isvalid = ST_IsValid(wkt);
update bgt_wegdeel set col_isvalid = ST_IsValid(wkt);
update bgt_paal set col_isvalid = ST_IsValid(wkt);
update bgt_kunstwerkdeel set col_isvalid = ST_IsValid(wkt);
