alter table bgt_begroeidterreindeel add column col_xmin decimal(7,1); 
alter table bgt_begroeidterreindeel add column col_xmax decimal(7,1); 
alter table bgt_begroeidterreindeel add column col_ymin decimal(7,1); 
alter table bgt_begroeidterreindeel add column col_ymax decimal(7,1);
alter table bgt_ondersteunendwaterdeel add column col_xmin decimal(7,1); 
alter table bgt_ondersteunendwaterdeel add column col_xmax decimal(7,1); 
alter table bgt_ondersteunendwaterdeel add column col_ymin decimal(7,1); 
alter table bgt_ondersteunendwaterdeel add column col_ymax decimal(7,1);
alter table bgt_onbegroeidterreindeel add column col_xmin decimal(7,1); 
alter table bgt_onbegroeidterreindeel add column col_xmax decimal(7,1); 
alter table bgt_onbegroeidterreindeel add column col_ymin decimal(7,1); 
alter table bgt_onbegroeidterreindeel add column col_ymax decimal(7,1);
alter table bgt_ondersteunendwegdeel add column col_xmin decimal(7,1); 
alter table bgt_ondersteunendwegdeel add column col_xmax decimal(7,1); 
alter table bgt_ondersteunendwegdeel add column col_ymin decimal(7,1); 
alter table bgt_ondersteunendwegdeel add column col_ymax decimal(7,1);
alter table bgt_overbruggingsdeel add column col_xmin decimal(7,1); 
alter table bgt_overbruggingsdeel add column col_xmax decimal(7,1); 
alter table bgt_overbruggingsdeel add column col_ymin decimal(7,1); 
alter table bgt_overbruggingsdeel add column col_ymax decimal(7,1);
alter table overbruggingsdeel add column col_xmin decimal(7,1); 
alter table overbruggingsdeel add column col_xmax decimal(7,1); 
alter table overbruggingsdeel add column col_ymin decimal(7,1); 
alter table overbruggingsdeel add column col_ymax decimal(7,1);
alter table bgt_overigbouwwerk add column col_xmin decimal(7,1); 
alter table bgt_overigbouwwerk add column col_xmax decimal(7,1); 
alter table bgt_overigbouwwerk add column col_ymin decimal(7,1); 
alter table bgt_overigbouwwerk add column col_ymax decimal(7,1);
alter table bgt_pand add column col_xmin decimal(7,1); 
alter table bgt_pand add column col_xmax decimal(7,1); 
alter table bgt_pand add column col_ymin decimal(7,1); 
alter table bgt_pand add column col_ymax decimal(7,1);
alter table bgt_scheiding add column col_xmin decimal(7,1); 
alter table bgt_scheiding add column col_xmax decimal(7,1); 
alter table bgt_scheiding add column col_ymin decimal(7,1); 
alter table bgt_scheiding add column col_ymax decimal(7,1);
alter table bgt_tunneldeel add column col_xmin decimal(7,1); 
alter table bgt_tunneldeel add column col_xmax decimal(7,1); 
alter table bgt_tunneldeel add column col_ymin decimal(7,1); 
alter table bgt_tunneldeel add column col_ymax decimal(7,1);
alter table bgt_waterdeel add column col_xmin decimal(7,1); 
alter table bgt_waterdeel add column col_xmax decimal(7,1); 
alter table bgt_waterdeel add column col_ymin decimal(7,1); 
alter table bgt_waterdeel add column col_ymax decimal(7,1);
alter table bgt_wegdeel add column col_xmin decimal(7,1); 
alter table bgt_wegdeel add column col_xmax decimal(7,1); 
alter table bgt_wegdeel add column col_ymin decimal(7,1); 
alter table bgt_wegdeel add column col_ymax decimal(7,1);
alter table bgt_paal add column col_xmin decimal(7,1); 
alter table bgt_paal add column col_xmax decimal(7,1); 
alter table bgt_paal add column col_ymin decimal(7,1); 
alter table bgt_paal add column col_ymax decimal(7,1);
alter table bgt_kunstwerkdeel add column col_xmin decimal(7,1); 
alter table bgt_kunstwerkdeel add column col_xmax decimal(7,1); 
alter table bgt_kunstwerkdeel add column col_ymin decimal(7,1); 
alter table bgt_kunstwerkdeel add column col_ymax decimal(7,1);

update bgt_begroeidterreindeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_ondersteunendwaterdeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_onbegroeidterreindeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_ondersteunendwegdeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_overbruggingsdeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update overbruggingsdeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_overigbouwwerk set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_pand set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_scheiding set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_tunneldeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_waterdeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_wegdeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_paal set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
update bgt_kunstwerkdeel set col_xmin = ST_XMin(wkt), col_xmax = ST_XMax(wkt), col_ymin = ST_YMin(wkt), col_ymax = ST_YMax(wkt);
